version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: php:8.2-fpm
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - laravel_network
        depends_on:
            - postgres
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_DATABASE=devops_app
            - DB_USERNAME=admin
            - DB_PASSWORD=admin
        user: "${UID}:${GID}"

    webserver:
        image: nginx:latest
        container_name: laravel_webserver
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - laravel_network
        depends_on:
            - app
        ports:
            - "8080:80"

    postgres:
        image: postgres:13
        container_name: postgres_db
        environment:
            POSTGRES_DB: devops_app
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

volumes:
    pgdata:
        driver: local
